### ISSUE TITLE
Change a number in the FAQ

### ISSUE THREAD

**Issue by Yessin111** [Derpthemeus/ChampionMastery.GG#37]
The current FAQ says:
_Can you show everybody on the highscores (instead of just the top 25 players)?_

This should be updated to _50 players_.

Since I'm in a good mood, I'll write the code for you. Just change this line:
`{{#>question question="Can you show everybody on the highscores (instead of just the top 25 players)?"}}`

to this:
`{{#>question question="Can you show everybody on the highscores (instead of just the top 50 players)?"}}`

You're welcome 😎

**Comment by Derpthemeus** [comment]
Will be fixed in next deployment
